### ISSUE TITLE
webcontrol_parms 0: (broken) cameras still added when clicking Add camera in the webpage

### ISSUE THREAD

**Issue by eudoxos** [Motion-Project/motionplus#10]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: https://github.com/Motion-Project/motionplus/commit/596f935ab05e6d4294047e38e8a3b9e7ed53b0a5
2. installed as a package or compiled from sources [deb, rpm, git, other]: git
3. video stream source [V4L2, network camera(http, rtsp, etc), mmal]: v4l2
4. hardware [x86, ARM, other]: RaspberryPi Zero
5. operating system [18.04, Stretch, etc, FreeBSD, other]: Raspbian 10

I have `webcontrols_parms 0` in the configuration which, as I understand, should disable any configuration through the web interface. I still see the "Actions" menu item in the webpage; when I click "Add camera", I  see new camers (with the same name as the first one) being added to "Cameras"; they are not real, show no images, and disappear after restart.

![image](https://user-images.githubusercontent.com/1029876/126893923-2ad4b998-f653-4081-8228-a16a7891f333.png)

(As a side note, a way to disable all actions and config even appearing in the UI, would be nice)

(the git revision in the screenshot is not correct, that is the first revision which I compiled; it did not get updated after recompilation, I am really using the https://github.com/Motion-Project/motionplus/commit/596f935ab05e6d4294047e38e8a3b9e7ed53b0a5)

**Comment by Mr-Dave** [comment]
This has been on my todo list.  The add/delete/save need to be disabled for various `webcontrol_parms` values.

**Comment by Mr-Dave** [comment]
Closed via 96291c0e915daa0c8a448009fd2686d8dc62d087
