### ISSUE TITLE
Webpage contents uses webcontrol_port rather than real port

### ISSUE THREAD

**Issue by eudoxos** [Motion-Project/motionplus#11]
https://github.com/Motion-Project/motionplus/blob/596f935ab05e6d4294047e38e8a3b9e7ed53b0a5/src/webu.cpp#L337
As it happened, I was running motionplus through NAT tunnel and the webpage got broken (loaded, but not reacting and without contents). The reason was that the outer (tunneled) port was different from webcontrol_port. SImilar to how the *real* (client-facing) host address is obtained, the port should be also found form the actual connection. My workaround was to assign the same port numbers on the NAT as well as on the internal IP, but this is not always possible.

**Comment by Mr-DaveDev** [comment]
I'm not sure I am following.  Is it the situation that you changed the port via tunneling outside of Motionplus and your expectation is that Motionplus would figure out what you did and compensate in the generation of the webpage?

**Comment by eudoxos** [comment]
You are following, yes. For example: public IP 4.5.6.7:8000 → NAT → 192.168.0.5:3000.

Actually I only see now that you discard the port part from MHD_HTTP_HEADER_HOST, and then put back the guessed port number based on the config. So all those 4 lines could be deleted, and the problem is solved, as the header [will already contain the port if non-standard (80 for https, 443 for https)](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23).

https://github.com/Motion-Project/motionplus/blob/596f935ab05e6d4294047e38e8a3b9e7ed53b0a5/src/webu.cpp#L324-L327

While you are at that, you could also use [protocol-relative URL](https://en.wikipedia.org/wiki/Wikipedia:Protocol-relative_URL), so deleting 

https://github.com/Motion-Project/motionplus/blob/596f935ab05e6d4294047e38e8a3b9e7ed53b0a5/src/webu.cpp#L330-L336

and say just
```
 webui->hostfull += "//" + hostname;
```

This would help if Motionplus itself is run without TLS, but gets encrypted by a proxy later; then the client will be using `https:` but Motionplus will think it should be `http:`.

Don't understand me wrong, I appreciate all the work you put into Motion(plus), I just was not sure what was the solution when I reported the issue. Now I see the fix would not be that difficult. If you want, I will do a PR with those 2 changes.

**Comment by Mr-DaveDev** [comment]
Thanks.  A PR would be good for this.

**Comment by tosiara** [comment]
@Mr-DaveDev Would the legacy `motion` benefit from this change too? If I recall correctly, it also used to not work correctly behind the port forwarding NAT

**Comment by Mr-Dave** [comment]
It would not work for legacy Motion due to how that application has multiple ports for everything.
