### ISSUE TITLE
Docker container:  Could not open configuration file: No such file or directory

### ISSUE THREAD

**Issue by Tobus** [Motion-Project/motionplus#118]
### Did you read the guide?

Yes

### What is the base version number of MotionPlus being used?

0.1.x

### What was the install method?

Installed via package tool

### What is base architecture?

ARM-64bit

### What is the distro being used?

Raspbian

### Disto version number

bookworm

### Camera/Sound type(s) being used?

v4l2 camera

### Describe the issue/problem and steps to reproduce

When starting the docker container, following error is shown:
`[ALR][ALL][00:motionplus] conf_init: Could not open configuration file: No such file or directory`

I did not changes anything in motionplus-dist.conf

Does anybody know, what I am doign wrong?

Thanks
Tobias

### Relevant MotionPlus log output (at log_level 8)

```shell
[ALR][ALL][00:motionplus] conf_init: Could not open configuration file: No such file or directory
```

**Comment by micahed** [comment]
Did you rename motionplus-dist.conf to motionplus.conf ?

**Comment by Tobus** [comment]
oh, sorry. True!
