### ISSUE TITLE
compile failure with git head

### ISSUE THREAD

**Issue by gene-git** [Motion-Project/motionplus#120]
### Did you read the guide?

Yes

### What is the base version number of MotionPlus being used?

0.1.x

### What was the install method?

Built from source code

### What is base architecture?

x86/x64

### What is the distro being used?

Other

### Disto version number

arch linux (rolling release)

### Camera/Sound type(s) being used?

Network camera with RTSP

### Describe the issue/problem and steps to reproduce

FYI:

After commit b974849e5accb988bf4b42b0ad733297ed452ae6 

my daily builds of git head fail with:

```
libcam.cpp: In member function ‘void cls_libcam::cam_config_orientation()’:
libcam.cpp:511:29: error: ‘class libcamera::CameraConfiguration’ has no member named ‘orientation’
  511 |                     config->orientation = Orientation::Rotate0;
```

### Relevant MotionPlus log output (at log_level 8)

```shell
N/A
```

**Comment by Mr-Dave** [comment]
Can you tell me the contents of /usr/include/libcamera/libcamera/version.h

**Comment by gene-git** [comment]
/usr/include/libcamera/libcamera/version.h is owned by libcamera 0.1.0-2 which is the arch provided version - it has already been marked out of date so will likely be updated pretty soon - I'll give it a little while and  if not I will build the newer one.


Contents below - I assume I need to update to version 0.2.0 ?

Thank you :)


```
/* SPDX-License-Identifier: LGPL-2.1-or-later */
/*
 * Copyright (C) 2019, Google Inc.
 *
 * version.h - Library version information
 *
 * This file is auto-generated. Do not edit.
 */

#pragma once

#define LIBCAMERA_VERSION_MAJOR		0
#define LIBCAMERA_VERSION_MINOR		1
#define LIBCAMERA_VERSION_PATCH		0
```

**Comment by Mr-Dave** [comment]
Arg.  That is the same version as the Raspberry PI OS I built today which does have Orientation.  (Debian 12 has version 0.0.3).  I suppose it is possible that they changed the API/interface and released it without changing the version number.....

**Comment by gene-git** [comment]
looking at their git repo - class SensorConfiguration is defined in camera.g in 0.2.0 but not in 0.1.0

**Comment by gene-git** [comment]
Ah but may have been added for rpi earlier 

commit 40d50263f553c10f2ed8b30a6d473553c8163674
Author: Jacopo Mondi <jacopo.mondi@ideasonboard.com>
Date:   Thu Sep 21 18:55:41 2023 +0200

    libcamera: rpi: Handle SensorConfiguration
``````

**Comment by gene-git** [comment]
Anyway - no biggie I'll just change the PKGBUILD to require libcamera>=0.2.0 and wait a while  - arch devs are usually pretty good about updating. If not, will just build the newer one.

**Comment by Mr-Dave** [comment]
@kbingham  It seems that the libcamera version number may be insufficient to determine the breakage of the API for Transform going to Orientation. i.e. Version 0.1.0 on one distro has Transform vs 0.1.0 on a different distro has Orientation.  Can you tell us whether there is any alternative provided by libcamera to allow downstream applications to  make the distinction?  (For example, there is a different version number I should be using)

**Comment by kbingham** [comment]
Libcamera 0.1.0 doesn't have that feature changed. What I suspect is that you're hitting something like Raspberry Pi releasing with libcamera 0.1.0+xxx.

I've Tagged libcamera 0.2.0 today.
You should be able to match on that more accurately.

**Comment by kbingham** [comment]
> Anyway - no biggie I'll just change the PKGBUILD to require libcamera>=0.2.0 and wait a while  - arch devs are usually pretty good about updating. If not, will just build the newer one (actually build is done)
> 
> I think I'll let arch do it - turns out pipewire has dep on ibcamera.so=0.1-64 - so it will need to be rebuilt as well. Easier to wait at this point.
> 
> thanks. Shall we close this on grounds 'needs newer' dependencies to build?
> 

I think that's likely the right path. This will take a few days to filter through. Pipewire have already handled the updates for this and will then require libcamera>=0.2.0

**Comment by Mr-Dave** [comment]
Yes, Raspberry PI OS has version 0.1.0 and they removed Transform from it.  I think that right now I'll just have to just disable libcamera entirely until these version numbers across Raspberry PI OS, libcamera git/source and Arch get resolved.  Having different APIs across the same version number of upstream software just isn't acceptable.

**Comment by kbingham** [comment]
I can't control what other distributions do. I can only control what we do as upstream.

**Comment by gene-git** [comment]
If you want to support old and new without libcamera vesion, then perhaps you could  add a check in configure with a small test program which simply includes libcamera and has a variable instance of class SensorConfiguration. If compile succeeds then its available otherwise its not available.

**Comment by Mr-Dave** [comment]
Thanks Kieran for clarifying what is and isn't in the official upstream versions.  I think this needs to go back to RPI-OS.

**Comment by kbingham** [comment]
yes. Having tagged libcamera-0.2 yesterday, I would expect RPi to be doing a rebase on top of that as soon as they're able to.

**Comment by Mr-Dave** [comment]
closing via commit 886d379286f4484e9e6b752a8110af9ca54a3c0b

**Comment by gene-git** [comment]
thank you!
