### ISSUE TITLE
Captured recording freezes after random time. 

### ISSUE THREAD

**Issue by luqasz** [Motion-Project/motionplus#121]
### Did you read the guide?

Yes

### What is the base version number of MotionPlus being used?

0.1.x

### What was the install method?

Installed from deb

### What is base architecture?

x86/x64

### What is the distro being used?

Debian

### Disto version number

bookworm

### Camera/Sound type(s) being used?

Network camera with RTSP

### Describe the issue/problem and steps to reproduce

Captured recording freezes after random time. 
While playing recording (vlc and others), at random it freezes and after some random amount of seconds it continues, missing movement which is important. Seems like frames were dropped in recorded clip. 
I've bumped io and cpu priorities, but that didn't help.

### Relevant MotionPlus log output (at log_level 8)

```shell
Didn't capture since it happens at random.
```

**Comment by Mr-Dave** [comment]
I'll still need a log that shows all the configuration options

**Comment by luqasz** [comment]
```

**Comment by luqasz** [comment]
Main config file:
```
daemon off
setup_mode off
log_level 8
log_type ALL
native_language on
target_dir /mnt/motion

framerate 5

text_right %Y-%m-%d\n%T
text_scale 2

emulate_motion off
threshold 1200
threshold_tune off
noise_level 32
noise_tune off
despeckle_filter EedDl

minimum_motion_frames 2
event_gap 60
pre_capture 0
post_capture 0

picture_output off

movie_output on
movie_max_time 0
movie_quality 0
movie_filename %$/%Y.%m.%d_%H-%M-%S
movie_passthrough on

webcontrol_port 8080
webcontrol_localhost off
webcontrol_parms 0

stream_preview_scale 20
stream_preview_ptz off
stream_maxrate 25
stream_motion off
stream_quality 100
```
Camera config (all are same):
```
device_name garaz_38
device_id 207

netcam_high_url rtsp://x.x.x.x/cam/realmonitor?channel=1&subtype=0
netcam_url rtsp://x.x.x.x/cam/realmonitor?channel=1&subtype=1
netcam_userpass admin:admin
netcam_high_params capture_rate=25
netcam_params capture_rate=5

width 704
height 576
```

**Comment by Mr-Dave** [comment]
I believe this is caused by the lack of sufficient motion during the movie and no [post_capture](https://motion-project.github.io/motionplus_config.html#post_capture) frames being specified.  I'd recommend using the [post_capture](https://motion-project.github.io/motionplus_config.html#post_capture) to eliminate the freezes
