### ISSUE TITLE
movie_output_motion "on"  - produces only one frame in mp4 file

### ISSUE THREAD

**Issue by 2konrad** [Motion-Project/motionplus#133]
### Did you read the guide?

Yes

### What is the base version number of MotionPlus being used?

0.1.x

### What was the install method?

Built from source code

### What is base architecture?

ARM-64bit

### What is the distro being used?

Raspbian

### Disto version number

bookworm

### Camera/Sound type(s) being used?

PI camera via libcam

### Describe the issue/problem and steps to reproduce

The motion file with motion output (named `movie_filename` + "`m`" .`mp4`) is unusable. 

The error seems to come from the imgts being zero, which is sent to   `movie_put_image` 
 `movie_put_image(cam->movie_motion, &cam->imgs.image_motion , &cam->imgs.image_motion.imgts) == -1) {`

[                , &cam->imgs.image_motion.imgts) == -1) {](https://github.com/Motion-Project/motionplus/blob/ae72a8cc6573b9ca9855ad1fc112af014317aa0f/src/event.cpp#L354)

Part of the problem seems to be that `movie_reset_start_time` is not called for the motion video output.

### Relevant MotionPlus log output (at log_level 8)

```shell
No errors shown in log. 
av_write_frame seems to skip all frames after first one due to timing.
```

**Comment by Mr-Dave** [comment]
Thanks for reporting and finding underlying issue.  A fix will be pushed soon.
