### ISSUE TITLE
Text in upper left corner of event movies

### ISSUE THREAD

**Issue by zofer1** [Motion-Project/motionplus#144]
### Did you read the guide?

Yes

### What is the base version number of MotionPlus being used?

0.1.x

### What was the install method?

Installed via package tool

### What is base architecture?

x86/x64

### What is the distro being used?

Debian

### Disto version number

MX-23.2

### Camera/Sound type(s) being used?

v4l2 camera

### Describe the issue/problem and steps to reproduce

The event movie has a watermark on the upper left corner that I have found no way to disable or control
![left-corner-text](https://github.com/Motion-Project/motionplus/assets/6930947/d5be5b77-cdc0-47e0-8a19-784e203d3553)

### Relevant MotionPlus log output (at log_level 8)

```shell
Apr 29 17:21:07 [INF][ALL][00:motionplus] text_left
Apr 29 17:21:07 [INF][ALL][00:motionplus] text_right                %Y-%m-%d %T
Apr 29 17:21:07 [INF][ALL][00:motionplus] text_changes              off
Apr 29 17:21:07 [INF][ALL][00:motionplus] text_scale                1
Apr 29 17:21:07 [INF][ALL][00:motionplus] text_event                %Y%m%d%H%M%S
```

**Comment by Mr-Dave** [comment]
This is undocumented (in Motionplus).  Change the log_level to a value less than 8(Debug)

**Comment by zofer1** [comment]
Thanks for the details. You can close it or keep it open in order to update the documentation
