### ISSUE TITLE
Pictures are not taken with "best" mode

### ISSUE THREAD

**Issue by zofer1** [Motion-Project/motionplus#145]
### Did you read the guide?

Yes

### What is the base version number of MotionPlus being used?

0.1.x

### What was the install method?

Installed via package tool

### What is base architecture?

x86/x64

### What is the distro being used?

Other

### Disto version number

MX-23.2

### Camera/Sound type(s) being used?

v4l2 camera

### Describe the issue/problem and steps to reproduce

When using haar as second detection and configuring the below to capture the image used for tracking pictures are not taken.
The base folder of "Picture" is not even created and no errors appear in the log. In case the "best" picture in this case is the "/MotionPlus/src_haar.jpg" it does not follow the configured naming convention, it is in grey scale and is always overwritten. I assume this is part of the "log level (ALL)"

### Relevant MotionPlus log output (at log_level 8)

```shell
Apr 29 17:21:07 [NTC][ALL][00:motionplus] log_init: Using log type (ALL) log level (ALL)
...(omitted for clarity)
May 01 08:44:49 [INF][ALL][00:motionplus] picture_output            best
May 01 08:44:49 [INF][ALL][00:motionplus] picture_output_motion     off
May 01 08:44:49 [INF][ALL][00:motionplus] picture_type              jpg
May 01 08:44:49 [INF][ALL][00:motionplus] picture_quality           75
May 01 08:44:49 [INF][ALL][00:motionplus] picture_exif
May 01 08:44:49 [INF][ALL][00:motionplus] picture_filename          Picture/%Y/%m/%d/%$-%v-%Y%m%d%H%M%S-%q
...(omitted for clarity)
May 01 08:52:22 [NTC][ALL][00:ml00:Road] mlp_detected_trigger: Motion detected - starting event 3
May 01 08:52:22 [INF][ENC][00:ml00:Road] movie_set_quality: libx264 codec vbr/crf/bit_rate: 28
May 01 08:52:22 [NTC][EVT][00:ml00:Road] on_movie_start_command: File saved to: /MotionPlus/Video/2024/05/01/Road-03-20240501085222.mkv
May 01 08:52:22 [DBG][ALL][00:cv00:Road] algsec_image_label: Saved source image: /MotionPlus/src_haar.jpg
May 01 08:52:22 [DBG][ALL][00:cv00:Road] algsec_image_label: Above message repeats 9 times
May 01 08:53:24 [DBG][DBS][00:ml00:Road] dbse_sqlite3_exec: Executing query
May 01 08:53:24 [DBG][DBS][00:ml00:Road] dbse_sqlite3_exec: Finished query
May 01 08:53:24 [NTC][ALL][00:ml00:Road] mlp_actions_event: End of event 3
```

**Comment by Mr-Dave** [comment]
Looks like same kind of documentation problem as the other issue.  This is a file only saved when debug log level is specified.    In this situation, it is the source image that was sent into the haar processing.  Possibly snipped out of the log in this issue is the notification of saved best image.

**Comment by Mr-Dave** [comment]
Well, if you didn't get any "best" picture at all, that is a different bug....(I couldn't tell due to snipped log)
