### ISSUE TITLE
mjpeg streams

### ISSUE THREAD

**Issue by extorn** [Motion-Project/motionplus#17]
There is an issue at the moment with the streams. Because the client never cancels the request, as you navigate around the web ui, you open more and more streams.
Should this be resolved with a max stream length on the server that triggers the server to cancel the stream after a certain time has passed perhaps,  and or the client explicitly cancelling the load as they invoke different actions on the UI?

**Comment by Mr-Dave** [comment]
From my review, I do not see that it is opening more and more streams or connections.

**Comment by extorn** [comment]
I found this by navigating around and watching the connections in chrome developer mode. Each streaming video was opened as a 'page' was opened but never closed until the web ui was finally closed / loading stopped. It could be a quirk of chrome developer page I guess but it certainly continued to show data being loaded onto each stream image.



On 9 April 2022 04:45:15 BST, Mr-Dave ***@***.***> wrote:
>From my review, I do not see that it is opening more and more streams or connections.   
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/Motion-Project/motionplus/issues/17#issuecomment-1093648996
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Mr-Dave** [comment]
That is correct and technically different than the issue comment.  The page opens a connection to each of the streams and keeps it open.  I will look into it and put it into the large revisions that are currently waiting to be pushed

**Comment by extorn** [comment]
To clear I was referring to a single camera source. 

On 9 April 2022 14:32:39 BST, Mr-Dave ***@***.***> wrote:
>That is correct and technically different than the issue comment.  The page opens a connection to each of the streams and keeps it open.  I will look into it and put it into the large revisions that are currently waiting to be pushed
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/Motion-Project/motionplus/issues/17#issuecomment-1094025241
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Mr-Dave** [comment]
Resolved in latest commits.
