### ISSUE TITLE
Error: Dependency not satisfiable: libavcodec59

### ISSUE THREAD

**Issue by M4rc3lv** [Motion-Project/motionplus#175]
### Did you read the guide?

Yes

### What is the base version number of MotionPlus being used?

0.2.x

### What was the install method?

Installed via package tool

### What is base architecture?

x86/x64

### What is the distro being used?

Ubuntu

### Disto version number

Linux Mint 21.3 and Mint 22

### Camera/Sound type(s) being used?

v4l2 camera

### Describe the issue/problem and steps to reproduce

Unable to install on newer Linux versions like Mint 21.3 and Mint 22. It looks MotionPlus depends on libavcodec59, which seems to be an older version. Error "Error: Dependency not satisfiable: libavcodec59"

### Relevant MotionPlus log output (at log_level 8)

```shell
No log output since it can not be installed.
```

**Comment by Mr-Dave** [comment]
Motionplus does work with newer versions of ffmpeg.  Debs on the release page are for "Bookworm" (i.e. Debian).  

You would need to [build your own deb](https://motion-project.github.io/motionplus_build.html#Build_Deb) if you are not using Bookworm.  Note that you may need to adjust the script slightly to reflect the [newly reported issue](https://github.com/Motion-Project/motion-packaging/issues/22) if for some reason you need libcamera.
