### ISSUE TITLE
Ubuntu 24.04 had some updates. Since then, the 0.2.1 release does not compile anymore.

### ISSUE THREAD

**Issue by axeljerabek** [Motion-Project/motionplus#180]
### Did you read the guide?

Yes

### What is the base version number of MotionPlus being used?

0.2.x

### What was the install method?

Built from source code

### What is base architecture?

x86/x64

### What is the distro being used?

Ubuntu

### Disto version number

24.04

### Camera/Sound type(s) being used?

Network camera with RTSP, Network camera with HTTP

### Describe the issue/problem and steps to reproduce

Compile does not work anymore. There were some updates for the 24.04 distribution last week on the libav packages i think.

Output from fresh source:

webu_mpegts.cpp: In function ‘int webu_mpegts_open(ctx_webui*)’:
webu_mpegts.cpp:332:17: error: invalid conversion from ‘int (*)(void*, uint8_t*, int)’ {aka ‘int (*)(void*, unsigned char*, int)’} to ‘int (*)(void*, const uint8_t*, int)’ {aka ‘int (*)(void*, const unsigned char*, int)’} [-fpermissive]
  332 |         , NULL, &webu_mpegts_avio_buf, NULL);
      |                 ^~~~~~~~~~~~~~~~~~~~~
      |                 |
      |                 int (*)(void*, uint8_t*, int) {aka int (*)(void*, unsigned char*, int)}
In file included from /usr/include/x86_64-linux-gnu/libavformat/avformat.h:319:
/usr/include/x86_64-linux-gnu/libavformat/avio.h:404:25: note:   initializing argument 6 of ‘AVIOContext* avio_alloc_context(unsigned char*, int, int, void*, int (*)(void*, uint8_t*, int), int (*)(void*, const uint8_t*, int), int64_t (*)(void*, int64_t, int))’
  404 |                   int (*write_packet)(void *opaque, const uint8_t *buf, int buf_size),
      |                   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:497: webu_mpegts.o] Fehler 1
make[2]: Verzeichnis „/home/axel/dev/motionplus/motionplus-0.2.1/motionplus-release-0.2.1/src“ wird verlassen
make[1]: *** [Makefile:567: all-recursive] Fehler 1
make[1]: Verzeichnis „/home/axel/dev/motionplus/motionplus-0.2.1/motionplus-release-0.2.1“ wird verlassen
make: *** [Makefile:411: all] Fehler 2
root@home:/home/axel/dev/motionplus/motionplus-0.2.1/motionplus-release-0.2.1#

### Relevant MotionPlus log output (at log_level 8)

```shell
none
```

**Comment by Mr-Dave** [comment]
Pretty sure this is resolved in the master branch.  Commit 06b8fe6 handled most of it.

**Comment by axeljerabek** [comment]
That was the other bug I reported. The master branch compiles, runs, but dies after a short while. Cannot see why.

**Comment by axeljerabek** [comment]
yes, confirm. Tested everything and it is rockstable again. Bug is gone :)
