### ISSUE TITLE
Memory leak in timelapse feature

### ISSUE THREAD

**Issue by adrianmay** [Motion-Project/motionplus#191]
### Did you read the guide?

Yes

### What is the base version number of MotionPlus being used?

0.2.x

### What was the install method?

Built from source code

### What is base architecture?

x86/x64

### What is the distro being used?

Other

### Disto version number

Arch

### Camera/Sound type(s) being used?

Sound via PulseAudio

### Describe the issue/problem and steps to reproduce

With these settings ...

timelapse_interval 1
timelapse_mode daily
timelapse_fps 30
timelapse_container mpg
timelapse_filename %Y%m%d-timelapse

... motionplus terminates with OOM after about 20 minutes on a NUX with 8GB RAM doing very little else. 

Turning it off, all is well, but then I don't have the timelapse videos.

### Relevant MotionPlus log output (at log_level 8)

```shell
There are no relevant log entries even at maximum verbosity. It just closes with OOM. I see no reason why valgrind wouldn't go straight to it. I'll test any patch if you like.

MotionPlus version 0.2.0-git-20240909-2ef32fe
```

**Comment by Mr-Dave** [comment]
This isn't sufficient information to investigate.  The log at a debug level is needed.

**Comment by adrianmay** [comment]
Now that I got everything working I don't really want to break it again. But I think if you run your code in valgrind with the timelapse enabled it'll tell you precisely which malloc you're leaking from.

**Comment by adrianmay** [comment]
I'm not seeing a patch so unless I'm blind the leak is still there. Closing it as completed suggests it's been fixed.

**Comment by Mr-Dave** [comment]
With the response 

> Now that I got everything working I don't really want to break it again

you indicated you wouldn't be engaged.  There are also multiple problems with this issue. 

- Generally no log = no problem
- Just because a user doesn't see anything in log doesn't mean others wouldn't.
- The information provided in the issue isn't correct (sound device specified but reporting a camera issue)
- Version being used is not the most recent commit. 

That said, I do run valgrind on the application and address items as they are observed.

**Comment by adrianmay** [comment]
So you decided not to work the issue. Fair enough, but why mark it as if you'd fixed it? Others might be more tenacious but now it won't even come up on their radar. 

Has anybody run valgrind with the timelapse enabled?

**Comment by adrianmay** [comment]
Oh cool. I just assumed otherwise cos I saw no merge. Thanks!
