### ISSUE TITLE
100% CPU core utilization when two cameras used

### ISSUE THREAD

**Issue by restorepoint1** [Motion-Project/motionplus#198]
### Did you read the guide?

Yes

### What is the base version number of MotionPlus being used?

0.2.x

### What was the install method?

Built from source code

### What is base architecture?

x86/x64

### What is the distro being used?

Ubuntu

### Disto version number

24.04

### Camera/Sound type(s) being used?

Network camera with RTSP

### Describe the issue/problem and steps to reproduce

100% cpu utilization when two cameras are configured. cam1 only or cam2 only doesn't trigger the issue.
d1560c9 and above are affected commits, 2d24677 and below are not affected

[htop.txt](https://github.com/user-attachments/files/18113823/htop.txt)
[journalctl.txt](https://github.com/user-attachments/files/18113824/journalctl.txt)

### Relevant MotionPlus log output (at log_level 8)

```shell
Attached
```

**Comment by Mr-Dave** [comment]
For the HTOP output, it would be helpful to see the thread names.

**Comment by restorepoint1** [comment]
[htop_threads.txt](https://github.com/user-attachments/files/18123798/htop_threads.txt)

**Comment by Mr-Dave** [comment]
The thread view was the key.  (The problem was in the database module).  Fix will be pushed in shortly.
