### ISSUE TITLE
Unable to unpause via webinterface/post action

### ISSUE THREAD

**Issue by AlexBolton** [Motion-Project/motionplus#199]
### Did you read the guide?

Yes

### What is the base version number of MotionPlus being used?

0.2.x / preview commit 3e28491

### What was the install method?

Built from source code

### What is base architecture?

x86/x64

### What is the distro being used?

Ubuntu

### Disto version number

24.04.1 LTS

### Camera/Sound type(s) being used?

v4l2 camera

### Describe the issue/problem and steps to reproduce

A camera paused via the pause action or via the "pause" configuration perimeter  is unable to be unpaused.

[motionplus.conf.txt](https://github.com/user-attachments/files/18113884/motionplus.conf.txt)
[camera1.conf.txt](https://github.com/user-attachments/files/18113885/camera1.conf.txt)

### Relevant MotionPlus log output (at log_level 8)

```shell
[NTC][ALL][cl101:Camera1] init: Camera 101 started: motion detection enabled
[DBG][STR][wc00] parseurl: Sent url: /
[DBG][STR][wc00] parseurl: Decoded url: /
[DBG][STR][wc00] parms_edit: camid: >< camindx: >-1< cmd1: >< cmd2: >< cmd3: ><
[INF][ALL][wc00] client_connect: Connection from: 192.168.0.50
[DBG][ALL][wc00] hostname_get: Full Host:  //pram:8080
[DBG][ALL][wc00] Above message repeats 1 times
[DBG][STR][wc00] parse_cmd: key: command  value: pause 
[DBG][STR][wc00] parse_cmd: key: camid  value: 0 
[DBG][STR][wc00] parse_cmd: key: user  value:  
[DBG][STR][wc00] parseurl: Sent url: /
[DBG][STR][wc00] parseurl: Decoded url: /
[DBG][STR][wc00] parms_edit: camid: >< camindx: >-1< cmd1: >< cmd2: >< cmd3: ><
[DBG][ALL][wc00] hostname_get: Full Host:  //pram:8080
[DBG][ALL][wc00] Above message repeats 1 times
[DBG][STR][wc00] parse_cmd: key: command  value: unpause 
[DBG][STR][wc00] parse_cmd: key: camid  value: 0 
[DBG][STR][wc00] parse_cmd: key: user  value:
```

**Comment by AlexBolton** [comment]
Things work fine with release 0.2.2 (3f0dab2), if I had to hazard a guess it might be tied into the user_pause changes with 2d24677?

**Comment by Mr-Dave** [comment]
Confirmed.  Thanks for reporting.  Yes it is the working schedule revision and determining how to integrate user requests into scheduled pauses.
