### ISSUE TITLE
src/mmalcam.cpp function mmalcam_cleanup is still referencing util_free_var

### ISSUE THREAD

**Issue by northernb39** [Motion-Project/motionplus#4]
src/mmalcam.cpp function mmalcam_cleanup is still referencing util_free_var which appears to have been removed elsewhere in commit da16381a7ce5b09f22ff9d108d5c1b762b6069bc.

https://github.com/Motion-Project/motionplus/blob/c38fc57cf4253e59852d0faed8c4f35f954a9c3c/src/mmalcam.cpp#L385-L387

**Comment by Mr-DaveDev** [comment]
Thank you.  That function did not work as well as I had hoped.   In fact, valgrind told me it didn't work at all.  I'll push a commit later .
