### ISSUE TITLE
v4l2 set errors

### ISSUE THREAD

**Issue by Garbalovina07** [Motion-Project/motionplus#42]
### Did you read the guide?

Yes

### What is the base version number of MotionPlus being used?

0.1.x

### What was the install method?

Installed via package tool

### What is base architecture?

ARM-64bit

### What is the distro being used?

Raspbian

### Disto version number

Bullseye

### Camera/Sound type(s) being used?

v4l2 camera, PI camera via libcam

### Describe the issue/problem and steps to reproduce

I’m trying to use motionplus on a raspberry pi zero with the cpi camera 
I’ve configured my motionplus.conf and camera1.conf files

But after a few hours of research, I still have 2 errors I can’t solve

`[ERR][VID][00:ml00:OV5647] v4l2_set_fps: Error setting fps. Return code -1
[ERR][VID][00:ml00:OV5647] v4l2_set_mmap: Error starting stream. VIDIOC_STREAMON: Argument invalide`

How can I set this up ?

Thanks

### Relevant MotionPlus log output (at log_level 8)

```shell
[ERR][VID][00:ml00:OV5647] v4l2_set_fps: Error setting fps. Return code -1
[ERR][VID][00:ml00:OV5647] v4l2_set_mmap: Error starting stream. VIDIOC_STREAMON: Argument invalide
```

**Comment by Mr-Dave** [comment]
Is there a full log rather than a snippet?  

Was this started with `libcamerify motionplus` ?  

Rather than using v4l2 you could also try to use the libcamera directly by using `libcam_device camera0`

**Comment by Garbalovina07** [comment]
@Mr-Dave 

> Is there a full log rather than a snippet?

> [NTC][ALL][00:motionplus] conf_process: Processing config file /etc/motionplus/motionplus.conf
[ALR][ALL][00:motionplus] conf_edit_set_depr: "movie_codec" replaced with "movie_container" after version 0.0.1
[NTC][ALL][00:motionplus] conf_process: Processing config file /etc/motionplus/camera1.conf
[NTC][ALL][00:motionplus] log_init: Logging to syslog
[NTC][ALL][00:motionplus] log_init: MotionPlus 0.1.0 started
[NTC][ALL][00:motionplus] log_init: Using log type (ALL) log level (NTC)
[NTC][ALL][00:motionplus] mytranslate_init: Language: English
[NTC][STR][00:motionplus] webu_init_webcontrol: Starting webcontrol on port 8080
[NTC][STR][00:motionplus] webu_init_webcontrol: Started webcontrol on port 8080
[NTC][ENC][00:motionplus] movie_global_init: libavcodec  version 58.91.100
[NTC][ENC][00:motionplus] movie_global_init: libavformat version 58.45.100
[NTC][ALL][00:motionplus] main: Motionplus pid: 1175
[NTC][VID][00:ml00:OV5647] v4l2_start: Opening V4L2 device
[NTC][VID][00:ml00:OV5647] v4l2_device_open: Opening video device /dev/video0
[NTC][VID][00:ml00:OV5647] v4l2_set_input: Name = "unicam-image"- CAMERA
[NTC][VID][00:ml00:OV5647] v4l2_pixfmt_try: Testing palette GBRG (640x480)
[NTC][VID][00:ml00:OV5647] v4l2_pixfmt_set: Using palette GBRG (640x480)
[ERR][VID][00:ml00:OV5647] v4l2_set_fps: Error setting fps. Return code -1
[ERR][VID][00:ml00:OV5647] v4l2_set_mmap: Error starting stream. VIDIOC_STREAMON: Argument invalide
[ERR][VID][00:ml00:OV5647] v4l2_start: V4L2 device failed to open
[NTC][VID][00:ml00:OV5647] v4l2_cleanup: Closing video device /dev/video0
[ERR][ALL][00:ml00:OV5647] mlp_init_cam_start: Failed to start camera.
[NTC][ALL][00:ml00:OV5647] mlp_ring_resize: Resizing buffer to 4 items
[ERR][ALL][00:ml00:OV5647] mlp_init_firstimage: Unable to open camera
[NTC][ALL][00:ml00:OV5647] mlp_main: Exiting
[NTC][ALL][00:motionplus] main: Motionplus devices finished
[NTC][ALL][00:motionplus] main: MotionPlus terminating

It was started by `motionplus` 
`libcamerify motionplus` returns unknown command
Using `libcam_device camera0` instead of `v4l2_device` seems to solve the problem

>[NTC][ALL][00:motionplus] conf_process: Processing config file /etc/motionplus/motionplus.conf
[ALR][ALL][00:motionplus] conf_edit_set_depr: "movie_codec" replaced with "movie_container" after version 0.0.1
[NTC][ALL][00:motionplus] conf_process: Processing config file /etc/motionplus/camera1.conf
[NTC][ALL][00:motionplus] log_init: Logging to syslog
[NTC][ALL][00:motionplus] log_init: MotionPlus 0.1.0 started
[NTC][ALL][00:motionplus] log_init: Using log type (ALL) log level (NTC)
[NTC][ALL][00:motionplus] mytranslate_init: Language: English
[NTC][STR][00:motionplus] webu_init_webcontrol: Starting webcontrol on port 8080
[NTC][STR][00:motionplus] webu_init_webcontrol: Started webcontrol on port 8080
[NTC][ENC][00:motionplus] movie_global_init: libavcodec  version 58.91.100
[NTC][ENC][00:motionplus] movie_global_init: libavformat version 58.45.100
[NTC][ALL][00:motionplus] main: Motionplus pid: 1193
[NTC][VID][00:ml00:OV5647] libcam_start: Opening libcam
[NTC][VID][00:ml00:OV5647] libcam_start: Starting experimental libcamera .
[NTC][VID][00:ml00:OV5647] libcam_start: EXPECT crashes and hung processes!!!
[NTC][VID][00:ml00:OV5647] cam_start_params: Starting.
[NTC][VID][00:ml00:OV5647] cam_start_params: Finished.
[NTC][VID][00:ml00:OV5647] cam_start_mgr: Starting.
[6:26:21.957545389] [1206]  INFO Camera camera_manager.cpp:299 libcamera v0.0.4+22-923f5d70
[6:26:22.297143989] [1207]  INFO RPI raspberrypi.cpp:1476 Registered camera /base/soc/i2c0mux/i2c@1/ov5647@36 to Unicam device /dev/media3 and ISP device /dev/media0
[NTC][VID][00:ml00:OV5647] cam_start_mgr: cam_mgr started.
[NTC][VID][00:ml00:OV5647] cam_start_mgr: Finished.
[NTC][VID][00:ml00:OV5647] cam_start_config: Starting.
[NTC][VID][00:ml00:OV5647] cam_start_config: Configuration is valid
[6:26:22.315774858] [1206]  INFO Camera camera.cpp:1028 configuring streams: (0) 640x480-YUV420
[6:26:22.317755844] [1207]  INFO RPI raspberrypi.cpp:851 Sensor: /base/soc/i2c0mux/i2c@1/ov5647@36 - Selected sensor
format: 640x480-SGBRG10_1X10 - Selected unicam format: 640x480-pGAA
[NTC][VID][00:ml00:OV5647] cam_start_config: Finished.
[NTC][VID][00:ml00:OV5647] cam_start_req: Starting.
[NTC][VID][00:ml00:OV5647] cam_start_req: Finished.
[NTC][VID][00:ml00:OV5647] cam_start_capture: Starting.
[NTC][VID][00:ml00:OV5647] cam_start_capture: Finished.
[NTC][VID][00:ml00:OV5647] cam_start: Started all.
[NTC][ALL][00:ml00:OV5647] mlp_ring_resize: Resizing buffer to 4 items
[NTC][ALL][00:ml00:OV5647] mlp_init: Camera 1 started: motion detection Enabled

Thank you for the quick response
