### ISSUE TITLE
bad cseq

### ISSUE THREAD

**Issue by buteomont** [Motion-Project/motionplus#57]
### Did you read the guide?

Yes

### What is the base version number of MotionPlus being used?

0.1.x

### What was the install method?

Built from source code

### What is base architecture?

ARM-64bit

### What is the distro being used?

Raspbian

### Disto version number

bullseye

### Camera/Sound type(s) being used?

Network camera with RTSP

### Describe the issue/problem and steps to reproduce

If run at log level 8, the motionplus log continuously gets hundreds of the warning messages shown in the log snippet below.  Out of 7 cameras being controlled by MotionPlus, this one (a ReoLink, I believe) is the only one that creates these entries.  However, viewing the same camera using ffplay or other software does not show any errors like this.  A google search indicates that this may be caused by insufficient time between closing and opening a stream.  It doesn't cause any other problems afaik. 

### Relevant MotionPlus log output (at log_level 8)

```shell
Apr 19 08:44:16 [INF][ENC][16:nc16:pumpYard] movie_avcodec_log: RTP: PT=61: bad cseq 6d5b expected=6f23
Apr 19 08:44:16 [INF][ENC][16:nc16:pumpYard] movie_avcodec_log: RTP: PT=60: bad cseq 8a77 expected=0a5e
Apr 19 08:44:16 [INF][ENC][16:nc16:pumpYard] movie_avcodec_log: RTP: PT=60: bad cseq 0a5e expected=8a79
Apr 19 08:44:16 [INF][ENC][16:nc16:pumpYard] movie_avcodec_log: RTP: PT=60: bad cseq 8a79 expected=0a60
Apr 19 08:44:16 [INF][ENC][16:nc16:pumpYard] movie_avcodec_log: RTP: PT=60: bad cseq 0a60 expected=8a7d
Apr 19 08:44:16 [INF][ENC][16:nc16:pumpYard] movie_avcodec_log: RTP: PT=61: bad cseq 6d5d expected=6f25
Apr 19 08:44:16 [INF][ENC][16:nc16:pumpYard] movie_avcodec_log: RTP: PT=60: bad cseq 8a7d expected=0a62
Apr 19 08:44:16 [INF][ENC][16:nc16:pumpYard] movie_avcodec_log: RTP: PT=61: bad cseq 6d5f expected=6f27
```

**Comment by Mr-Dave** [comment]
These are messages directly from the ffmpeg av libs.  I'd bet that if you increased the warning level on ffplay you'd see the same thing.  

i.e. ffplay -loglevel warning "rtsp://xxx.xx.xxx:554/whatever"

Probably need an [enhancement](https://github.com/Motion-Project/motionplus/discussions/56) in MotionPlus to allow users change the log level of these av messages.

**Comment by buteomont** [comment]
I tried the **-loglevel warning** in _ffplay_ for both the hi-res and lo-res streams, and got a few "missed packet" warnings and such, but didn't get any of the **_bad cseq_** messages.  This is not a high priority problem, I just wanted to document it.

**Comment by Mr-Dave** [comment]
Closing.  This is probably related to the camera as well as the capture rates that are specified.
