### ISSUE TITLE
Movie file overwritten if new event occurs before previous file is finished writing to disk

### ISSUE THREAD

**Issue by buteomont** [Motion-Project/motionplus#58]
### Did you read the guide?

Yes

### What is the base version number of MotionPlus being used?

0.1.x

### What was the install method?

Built from source code

### What is base architecture?

ARM-64bit

### What is the distro being used?

Raspbian

### Disto version number

bullseye

### Camera/Sound type(s) being used?

Network camera with RTSP

### Describe the issue/problem and steps to reproduce

This was evasive but I finally caught it occurring. I'm not sure I fully understand what's going on, but here is my guess.
It seems that, after a relatively long event occurs, it takes a bit of time to write the movie file to disk.  If motion is detected during that time, the event number and conversion specifiers are **not** updated, and the new event is processed and written to disk.  In my case, since I'm using the conversion specifiers in the filename, that means that the last not-yet-fully-written movie is overwritten by the new movie.  
The abbreviated log below has only the event entries for the one camera that I was watching.  The last 14 lines show the file being overwritten.  There were many previous events on that camera that were processed correctly, but it started raining and generating events (I think) faster than they could be written to (external USB) disk. 

In my main configuration file, I have 

```
text_event %Y%m%d%H%M%S
movie_filename %Y-%m-%d/%t-%v-%C
```

I can provide more detailed (level 6) logs of this if needed.  I didn't post them here because Github doesn't seem to like large logs like that.

### Relevant MotionPlus log output (at log_level 8)

```shell
Apr 21 19:15:13 [NTC][EVT][03:ml03:shed] event_newfile: File saved to: /var/www/html/cams/shed/2023-04-21/4-745-20230421191312.mp4
Apr 21 19:17:19 [NTC][EVT][03:ml03:shed] event_newfile: File saved to: /var/www/html/cams/shed/2023-04-21/4-745-20230421191312.mp4
Apr 21 19:19:19 [NTC][EVT][03:ml03:shed] event_newfile: File saved to: /var/www/html/cams/shed/2023-04-21/4-745-20230421191312.mp4
Apr 21 19:20:46 [NTC][EVT][03:ml03:shed] event_newfile: File saved to: /var/www/html/cams/shed/2023-04-21/4-745-20230421191312.jpg
Apr 21 19:20:46 [NTC][EVT][03:ml03:shed] event_newfile: File saved to: /var/www/html/cams/shed/2023-04-21/4-746-20230421192046.mp4
Apr 21 19:21:37 [NTC][EVT][03:ml03:shed] event_newfile: File saved to: /var/www/html/cams/shed/2023-04-21/4-746-20230421192046.jpg
Apr 21 19:22:25 [NTC][EVT][03:ml03:shed] event_newfile: File saved to: /var/www/html/cams/shed/2023-04-21/4-01-20230421192224.mp4
Apr 21 19:24:26 [NTC][EVT][03:ml03:shed] event_newfile: File saved to: /var/www/html/cams/shed/2023-04-21/4-01-20230421192224.mp4
Apr 21 19:26:26 [NTC][EVT][03:ml03:shed] event_newfile: File saved to: /var/www/html/cams/shed/2023-04-21/4-01-20230421192224.mp4
Apr 21 19:28:27 [NTC][EVT][03:ml03:shed] event_newfile: File saved to: /var/www/html/cams/shed/2023-04-21/4-01-20230421192224.mp4
Apr 21 19:30:26 [NTC][EVT][03:ml03:shed] event_newfile: File saved to: /var/www/html/cams/shed/2023-04-21/4-01-20230421192224.mp4
Apr 21 19:32:27 [NTC][EVT][03:ml03:shed] event_newfile: File saved to: /var/www/html/cams/shed/2023-04-21/4-01-20230421192224.mp4
Apr 21 19:34:26 [NTC][EVT][03:ml03:shed] event_newfile: File saved to: /var/www/html/cams/shed/2023-04-21/4-01-20230421192224.mp4
Apr 21 19:36:26 [NTC][EVT][03:ml03:shed] event_newfile: File saved to: /var/www/html/cams/shed/2023-04-21/4-01-20230421192224.mp4
Apr 21 19:38:26 [NTC][EVT][03:ml03:shed] event_newfile: File saved to: /var/www/html/cams/shed/2023-04-21/4-01-20230421192224.mp4
Apr 21 19:40:26 [NTC][EVT][03:ml03:shed] event_newfile: File saved to: /var/www/html/cams/shed/2023-04-21/4-01-20230421192224.mp4
Apr 21 19:42:26 [NTC][EVT][03:ml03:shed] event_newfile: File saved to: /var/www/html/cams/shed/2023-04-21/4-01-20230421192224.mp4
Apr 21 19:44:26 [NTC][EVT][03:ml03:shed] event_newfile: File saved to: /var/www/html/cams/shed/2023-04-21/4-01-20230421192224.mp4
Apr 21 19:46:26 [NTC][EVT][03:ml03:shed] event_newfile: File saved to: /var/www/html/cams/shed/2023-04-21/4-01-20230421192224.mp4
Apr 21 19:48:26 [NTC][EVT][03:ml03:shed] event_newfile: File saved to: /var/www/html/cams/shed/2023-04-21/4-01-20230421192224.mp4
```

**Comment by Mr-Dave** [comment]
is the movie_max_time equal to 120?

**Comment by Mr-Dave** [comment]
I think I may see the issue.  You are using:
```
text_event %Y%m%d%H%M%S
movie_filename %Y-%m-%d/%t-%v-%C
```
Now text event is defined for the "event" and it is the one with the timestamp.  It is therefore going to get set at the start of the event.  This is then appended to the movie file name.  This all works wonderfully if the events are all short and fit into the allotted time permitted for the movie.  

What it would not handle well is the situation where there is a long event that spans an extended time period.  i.e. One that 14x the movie_max_time.  In this situation, there are multiple movies per event but the %C is only updated per event.

Instead of putting the time spec into the %C specifier, use it within the movie_name parameter.  e.g.
```
text_event 
movie_filename %Y-%m-%d/%t-%v-%Y%m%d%H%M%S
```
