### ISSUE TITLE
defunct sh processes accumulating after each exec command

### ISSUE THREAD

**Issue by tonytw1** [Motion-Project/motionplus#77]
### Did you read the guide?

Yes

### What is the base version number of MotionPlus being used?

0.1.x

### What was the install method?

Installed via package tool

### What is base architecture?

ARM-64bit

### What is the distro being used?

Raspbian

### Disto version number

20.04 bullseye

### Camera/Sound type(s) being used?

PI camera via libcam

### Describe the issue/problem and steps to reproduce

After migrating from motion to motionplus and the libcam on a fresh Raspberry Pi OS Lite (64-bit Bullseye) to access a Pi Camera module 3, `on_picture_saved` calls stopped working after motionplus had been running for a few hours.

This seems to be related to a large number of `defunct` `sh` processes with a parent matching the motionplus pid.
Restarting motionplus cleared out the defunct processes and service resumed for a while.
Likely some sort of maximum process limit preventing anymore exec calls.

I was able to resolve this locally be issuing a `signal(SIGCHLD,SIG_IGN)` before forking in exec_command.

The `util_exec_command` in motionplus is nearly identical to that in `motion` so I do not understand this  has started happening.
I'll attach a PR showing the change which worked for me but I'm a Java developer with limited C++ knowledge so this should be taken with a grain of salt.

Please will feel to close this immediately if it's not helpful.

### Relevant MotionPlus log output (at log_level 8)

```shell
Nothing indicating an error.
```

**Comment by Mr-Dave** [comment]
I couldn't reproduce with a simple test script.  What occurs in the script being executed?  (Just wondering if there is something that occurs in it that may allow me to reproduce the problem).

**Comment by CRCinAU** [comment]
For what its worth, I don't see this either - and I use `on_event_start`, `on_event_end` and `on_picture_save` scripts.

**Comment by tonytw1** [comment]
I'm going to try a few more combinations of a spare device this week to see if I can narrow it down.

**Comment by davedoesdev** [comment]
Seeing this too. My event is:

```
on_movie_end echo %f | /home/david/scripts/on_movie_end.sh
````
