### ISSUE TITLE
spurious curly brackets (syntax error)

### ISSUE THREAD

**Issue by eudoxos** [Motion-Project/motionplus#9]
The current trunk has two extra `}`, removing them fixed the syntax error:
https://github.com/Motion-Project/motionplus/blob/3c321fb1d1b46b03e016feca1d9524da5ad8169b/src/raspicam/RaspiCamControl.c#L1065-L1067

**Comment by Mr-Dave** [comment]
Thank you for reporting.  Closed via 9cb3cd9120d81efbffc713db86db9f8f0abf2961
